---
version: "3.9"

services:
  mongo:
    # We are using this image because it automatically creates replica set
    # which is required by prisma
    # https://github.com/prisma/prisma/issues/8266
    image: prismagraphql/mongo-single-replica:4.4.3-bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
      INIT_WAIT_SEC: 3
    ports:
      - ${MONGO_PORT}:27017
